### ISSUE TITLE
TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by jackjackjack1998** [LemaireJean-Baptiste/eventstudy#5]
Hi, 
when I try to get the table --> event.results() it says: "TypeError: object of type 'map' has no len()"

How can I solve this issue? Please much needed

**Comment by pm0107** [comment]
I think the same issue was raised earlier this year. Not too sure if it has been resolved yet.

[https://github.com/LemaireJean-Baptiste/eventstudy/issues/2](url)

**Comment by LemaireJean-Baptiste** [comment]
Hello I pushed some recent updates on pip, and will push it also here on github soon.
Can you please try to update the package and its dependencies and let me know if it solves your issue.
I discovered some breaking changes in pandas (maybe also numpy) affecting the way the package works.

To do so:
```
pip install numpy --upgrade
pip install pandas --upgrade
pip install eventstudy --upgrade
```

Let me know if it solves your issue.
I will add panda and numpy version number in the requirements settings of the package.

**Comment by jackjackjack1998** [comment]
> I think the same issue was raised earlier this year. Not too sure if it has been resolved yet.
> 
> [https://github.com/LemaireJean-Baptiste/eventstudy/issues/2](url)

Thanks, I will try to contact that person!

**Comment by jackjackjack1998** [comment]
> Hello I pushed some recent updates on pip, and will push it also here on github soon.
> Can you please try to update the package and its dependencies and let me know if it solves your issue.
> I discovered some breaking changes in pandas (maybe also numpy) affecting the way the package works.
> 
> To do so:
> 
> ```
> pip install numpy --upgrade
> pip install pandas --upgrade
> pip install eventstudy --upgrade
> ```
> 
> Let me know if it solves your issue.
> I will add panda and numpy version number in the requirements settings of the package.

Hello, thanks for taking time to respond me. 

I pasted the upgrades, but it doesn't solve the problem. 

It also says the following, when trying to install "--upgrade": 
<img width="1092" alt="Screenshot 2020-10-16 at 11 23 41" src="https://user-images.githubusercontent.com/72874134/96241135-0d77b680-0fa2-11eb-864b-06ad3925f885.png">

If you have any advice, please let me know.

**Comment by pm0107** [comment]
.results() method works for me now. Thanks so much @LemaireJean-Baptiste

**Comment by jackjackjack1998** [comment]
Works. Thank you so much

___
________________________________

**Comment by LemaireJean-Baptiste** [comment]
Happy to hear that
